services:
  - type: web
    name: bloodbank-project
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn mysite.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DJANGO_SETTINGS_MODULE
        value: mysite.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: bloodbank-db
          property: connectionString
    healthCheckPath: /
    autoDeploy: true
    plan: free

databases:
  - name: bloodbank-db
    databaseName: bloodbank
    user: bloodbank_user
    plan: free
